# Qestion 2

In [106]:
import numpy as np
import pandas as pd
import json
json_file_path='data/world_bank_projects.json'
with open(json_file_path,'r') as json_file:
    json_data=json.load(json_file)
json_df=pd.DataFrame(json_data)
json_project_df=json_df.mjtheme_namecode
list_project=json_project_df.tolist()
project_name=[item for sublist in list_project for item in sublist]
project_name_df=pd.DataFrame(project_name)

In [107]:
project_name_df.name.value_counts().head(10)

Environment and natural resources management    223
Rural development                               202
Human development                               197
Public sector governance                        184
Social protection and risk management           158
Financial and private sector development        130
                                                122
Social dev/gender/inclusion                     119
Trade and integration                            72
Urban development                                47
Name: name, dtype: int64

# Question 3

In [108]:
project_name_df_empty=project_name_df[project_name_df.name=='']

In [109]:
project_name_df_empty.code.value_counts()

11    27
4     16
2     15
10    14
8     13
7     11
6     10
5      5
1      5
9      3
3      3
Name: code, dtype: int64

In [110]:
dict_projects={'1':'Economic management','2':'Public sector governance','3':'Rule of law','4':'Financial and private sector development',
               '5':'Trade and integration','6':'Social protection and risk management','7':'Social dev/gender/inclusion',
               '8':'Human development','9':'Urban development','10':'Rural development',
               '11':'Environment and natural resources management'}

In [111]:
project_name = project_name_df.applymap(lambda x: np.nan if x == '' else x)

In [112]:
project_name.head()

  code                                   name
0    8                      Human development
1   11                                    NaN
2    1                    Economic management
3    6  Social protection and risk management
4    5                  Trade and integration

In [114]:
project_name.ffill()

     code                                          name
0       8                             Human development
1      11                             Human development
2       1                           Economic management
3       6         Social protection and risk management
4       5                         Trade and integration
5       2                      Public sector governance
6      11  Environment and natural resources management
7       6         Social protection and risk management
8       7                   Social dev/gender/inclusion
9       7                   Social dev/gender/inclusion
10      5                         Trade and integration
11      4      Financial and private sector development
12      6         Social protection and risk management
13      6         Social protection and risk management
14      2                      Public sector governance
15      4      Financial and private sector development
16     11  Environment and natural resources management
17      8  Environment and natural resources management
18     10                             Rural development
19      7                             Rural development
20      2                      Public sector governance
21      2                      Public sector governance
22      2                      Public sector governance
23     10                             Rural development
24      2                             Rural development
25     10                             Rural development
26      6         Social protection and risk management
27      6         Social protection and risk management
28     11  Environment and natural resources management
29      4  Environment and natural resources management
...   ...                                           ...
1469    8                             Human development
1470    9                             Urban development
1471    6         Social protection and risk management
1472    6         Social protection and risk management
1473    9                             Urban development
1474    2                      Public sector governance
1475    2                      Public sector governance
1476   10                             Rural development
1477   11                             Rural development
1478    8                             Human development
1479    7                   Social dev/gender/inclusion
1480   11  Environment and natural resources management
1481    5  Environment and natural resources management
1482    6         Social protection and risk management
1483    8         Social protection and risk management
1484    4      Financial and private sector development
1485    7                   Social dev/gender/inclusion
1486    8                             Human development
1487    5                         Trade and integration
1488    2                      Public sector governance
1489    8                             Human development
1490   10                             Rural development
1491    6                             Rural development
1492   10                             Rural development
1493   10                             Rural development
1494   10                             Rural development
1495    9                             Urban development
1496    8                             Human development
1497    5                         Trade and integration
1498    4      Financial and private sector development

[1499 rows x 2 columns]

In [119]:
project_name_df=pd.DataFrame(project_name)